name: inspector

on:
  push:
    branches:
      - main
    paths:
      - 'inspector/**'
      - 'ui/**'

env:
  IMAGE_NAME: ghcr.io/mrsupiri/lazy-koala/inspector
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t $IMAGE_NAME:latest -f inspector/Dockerfile .
      - run: docker tag $IMAGE_NAME:latest $IMAGE_NAME:commit-${GITHUB_SHA:0:8}
      - run: docker push $IMAGE_NAME --all-tags
